=== a5adkhann/xml/ExternalDTD.dtd
<!ELEMENT students (Student*)>
    <!ELEMENT Student (name, age)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT age (#PCDATA)>

    <!-- <!ATTLIST Student id CDATA #REQUIRED> -->
    <!-- <!ATTLIST Student id CDATA #IMPLIED> -->
    <!ATTLIST Student id CDATA #FIXED "ABC">

=== a5adkhann/xml/DocumentTypeDefinition.xml
<?xml version="1.0"?>
<!DOCTYPE students SYSTEM "ExternalDTD.dtd" [
     <!ENTITY a "hello">
    <!ENTITY b "world">
]>
<students>
    
    <Student>
        <name>&a;</name>
        <age>23</age>
    </Student>

    <Student id="ABC">
        <name>&b;</name>
        <age>23</age>
    </Student>

    
    <Student>
        <name>Student3</name>
        <age>23</age>
    </Student>



</students>
